---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  FWaaS registry resource with PaloAltoNetworks::CloudNGFW::NGFW and
  rulestack resource with PaloAltoNetworks::CloudNGFW::RuleStack
Parameters:
  RSProgrammaticAccessToken:
    NoEcho: true
    Description: RuleStack resource Programmatic Access Token
    Type: String
    Default: >-
         
  FWProgrammaticAccessToken:
    NoEcho: true
    Description: Firewall resource Programmatic Access Token
    Type: String
    Default: >-

  FirewallName:
    Description: Enter your Firewall resource Name
    Type: String


    
  
  
Resources:
  RuleStackResource:
    Type: 'PaloAltoNetworks::CloudNGFW::RuleStack'
    Properties:
      RuleStackName: surajRSCFTupdated
      ProgrammaticAccessToken: !Ref RSProgrammaticAccessToken
      RuleStack:
        Scope: Local
        MinAppIdVersion: 8509-7158
        Description: For RuleStack
        Deploy: 'YES'
      SecurityObjects:
        FqdnList:
          Name: suraj-FQDN-name-updated
          FqdnList:
            - 30.1.1.0
            - 30.1.2.0
          AuditComment: Test Audit Comment
          Description: Desc FqdnList
        PrefixList:
          Name: suraj-prefix-name
          PrefixList:
            - 30.1.1.0/24
            - 30.1.2.0/24
          AuditComment: Test Audit Comment
          Description: Desc PrefixList
        CustomUrlCategory:
          URLTargets:
            - www.test.com
            - www.test2.com
            - www.test3.com
          Name: testUrlcateory
          Description: Desc CustomUrlCategory
          Action: allow
          AuditComment: test audit commment
        CertificateObject:
          Name: test-certificate-object
          Description: Certificate Object Description
          CertificateSignerArn: arntestSignarn
          CertificateSelfSigned: false
          AuditComment: test certificate audit comment
        IntelligentFeed:
          Name: test-IntelligentFeed
          Description: Test Intelligent feed Desc
          FeedURL: 'https://www.test.com'
          Type: URL_LIST
          Frequency: DAILY
          Time: 3
          AuditComment: test audit commment
      RuleList:
        - RuleListType: LocalRule
          RuleName: TestRule1
          Description: Test Security Rule 1 Description
          Action: DenyResetServer
          Protocol: application-default
          Priority: '5'
          Source:
            Cidrs:
              - 192.168.1.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-TorExitIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
            PrefixLists:
              - suraj-prefix-name
          Destination:
            Cidrs:
              - 192.168.2.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-BulletproofIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
              - PaloAltoNetworks-TorExitIPAddresses
            PrefixLists:
              - suraj-prefix-name
            FqdnLists:
              - suraj-FQDN-name-updated
          Category:
            URLCategoryNames:
              - testUrlcateory
            Feeds:
              - test-IntelligentFeed
          Applications:
            - any
        - RuleListType: LocalRule
          RuleName: TestRule2
          Description: Test Security Rule 2 Description
          Action: DenyResetServer
          Protocol: application-default
          Priority: '9'
          Source:
            Cidrs:
              - 192.168.1.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-TorExitIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
            PrefixLists:
              - suraj-prefix-name
          Destination:
            Cidrs:
              - 192.168.2.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-BulletproofIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
              - PaloAltoNetworks-TorExitIPAddresses
            PrefixLists:
              - suraj-prefix-name
            FqdnLists:
              - suraj-FQDN-name-updated
          Category:
            URLCategoryNames:
              - testUrlcateory
            Feeds:
              - test-IntelligentFeed
          Applications:
            - any
        - RuleListType: LocalRule
          RuleName: TestRule3
          Description: Test Security Rule 3 Description
          Action: DenyResetServer
          Protocol: application-default
          Priority: '8'
          Source:
            Cidrs:
              - 192.168.1.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-TorExitIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
            PrefixLists:
              - suraj-prefix-name
          Destination:
            Cidrs:
              - 192.168.2.0/24
            Countries: []
            Feeds:
              - PaloAltoNetworks-BulletproofIPAddresses
              - PaloAltoNetworks-HighRiskIPAddresses
              - PaloAltoNetworks-TorExitIPAddresses
            PrefixLists:
              - suraj-prefix-name
            FqdnLists:
              - suraj-FQDN-name-updated
          Category:
            URLCategoryNames:
              - testUrlcateory
            Feeds:
              - test-IntelligentFeed
          Applications:
            - any
  FirewallResource:
    DependsOn: RuleStackResource
    Type: 'PaloAltoNetworks::CloudNGFW::NGFW'
    Properties:
      Description: Test Firewall with Associate
      EndpointMode: CustomerManaged
      AutomaticUpgradeAppIdVersion:  True
      FirewallName: surajFWCFT
      RuleStackName: surajRSCFTupdated
      SubnetMappings:
        - us-east-1a
        - us-east-1b
      VpcId: vpc-0412056cda9c93645
      LogDestinationConfigs:
        - LogType: TRAFFIC
          LogDestinationType: S3
          LogDestination: testloggroupnew
        - LogType: THREAT
          LogDestinationType: CloudWatchLogs
          LogDestination: testthreatnew
        - LogType: DECRYPTION
          LogDestinationType: KinesisDataFirehose
          LogDestination: teskinessisnew
      ProgrammaticAccessToken: !Ref FWProgrammaticAccessToken
